num1=int(input("num 1 = "))
num2=int(input("num 2 = "))
print ("Sum is : ",num1+num2)
print ("Difference is : ",num1-num2)
print ("Product is : ",num1*num2)
print ("Dividend is : ",num1/num2)
num2=int(input())